apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: frontend
commonLabels:
  app.kubernetes.io/component: bos
  app.kubernetes.io/instance: testing
  app.kubernetes.io/name: bos-gateway
resources:
- ../../../base-0.0.0
- certificate.yaml
- frontend-config.yaml
- ingress.yaml
images:
- name: bos-gateway
  newName: europe-west3-docker.pkg.dev/calimero-ops/calimero/bos-gateway
  newTag: 8eb2f97
- name: bos-gateway-internal-production
  newName: europe-west3-docker.pkg.dev/calimero-ops/calimero/bos-gateway-internal-production
  newTag: v0.0.0-rc.10
- name: bos-gateway-mainnet
  newName: europe-west3-docker.pkg.dev/calimero-ops/calimero/bos-gateway-mainnet
  newTag: "00694e6"
- name: bos-gateway-staging
  newName: europe-west3-docker.pkg.dev/calimero-ops/calimero/bos-gateway-staging
  newTag: 19de5c0
- name: bos-gateway-testnet
  newName: europe-west3-docker.pkg.dev/calimero-ops/calimero/bos-gateway-testnet
  newTag: "00694e6"
- name: bos-gateway-workshop-staging
  newName: europe-west3-docker.pkg.dev/calimero-ops/calimero/bos-gateway-workshop-staging
  newTag: v0.0.0-rc.2
patches:
- path: deployment-patch.yaml
  target:
    kind: Deployment
