apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: frontend
resources:
- internal/
- portal/
images:
- name: bos-gateway-community-production
  newName: europe-west3-docker.pkg.dev/calimero-ops/calimero/bos-gateway-community-production
  newTag: 5dd637c
- name: bos-gateway-internal-production
  newName: europe-west3-docker.pkg.dev/calimero-ops/calimero/bos-gateway-internal-production
  newTag: 68a4b22
